version: '3'
services:
  # backend:
  #   build: .
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
